version: '3.1'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    environment:
      - MQTT_USER=user
      - MQTT_PASSWORD=1234
    restart: always
